//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int id { get; set; }
        public string uNo { get; set; }
        public string uAdi { get; set; }
        public string Yazar { get; set; }
        public string Yayinevi { get; set; }
        public string Fiyat { get; set; }
        public string Url { get; set; }
        public string Ozet { get; set; }
    }
}
